[project]
name = "robot-learning-cloth-folding"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
      "lerobot[dataset,sarm,training,feetech,viz,smolvla,molmoact2]",
      "pynput>=1.8.1",
      "torch",
      "torchvision",
]

[tool.uv.sources]
lerobot = { path = "molmoact2", editable = true }
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
